FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["firs-api.csproj", "./"]
COPY ["../api.Modelos", "../api.Modelos/"]
COPY ["../API.Result", "../API.Result/"]
RUN dotnet restore "firs-api.csproj"
COPY . .
RUN dotnet build "firs-api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "firs-api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "firs-api.dll"]